# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
GET http://localhost:3000/albums?pageSize=10&pageNum=1
Accept: application/json

###
GET http://localhost:3000/albums?keyword=测试专辑1
Accept: application/json


###

POST http://localhost:3000/albums
Content-Type: application/json

{
            "album_name": "新增专辑2",
            "public_time": "2017-12-12",
            "price": 100,
            "cover": "http://imgcache.qq.com/music/photo/album_300/08/300_albumpic_3751508_0.jpg",
            "singers": [
                {
                    "singer_id": "265",
                    "singer_name": "周杰伦"
                }
            ]
        }

###

put http://localhost:3000/albums
Content-Type: application/json

{
  "_id":"5e23fd6460472e305c7579b4",
  "album_name":"修改专辑2",
  "singers": [
        {
            "singer_id": "266",
            "singer_name": "王力宏1"
        }
    ]
}

###

DELETE http://localhost:3000/albums/5e23fd6460472e305c7579b4
Accept: application/json

###
GET http://localhost:3000/albums/detail/5e341ac7964bc0103dfca243
Accept: application/json

###

GET http://localhost:3000/albums/all
Accept: application/json

###